package hibernate;
// Generated 2018��8��22�� ����10:07:08 by Hibernate Tools 5.3.1.Final
//import javax.persistence.Entity;
//@Entity
/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private Integer id;
	private String name;

	public Person() {
	}

	public Person(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
